/**
 * \file
 *
 * \brief Widget ToolKit training widget
 *
 * Copyright (c) 2014-2018 Microchip Technology Inc. and its subsidiaries.
 *
 * \asf_license_start
 *
 * \page License
 *
 * Subject to your compliance with these terms, you may use Microchip
 * software and any derivatives exclusively with Microchip products.
 * It is your responsibility to comply with third party license terms applicable
 * to your use of third party software (including open source software) that
 * may accompany Microchip software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE,
 * INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY,
 * AND FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL MICROCHIP BE
 * LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL
 * LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO THE
 * SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE
 * POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE FULLEST EXTENT
 * ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN ANY WAY
 * RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 * THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * \asf_license_stop
 */
/*
 * Support and FAQ: visit <a href="https://www.microchip.com/support/">Microchip Support</a>
 */
#include <asf.h>
#include <stdio.h>

#include "app_widget.h"

/**
 * \brief Event command ID for the application widgets.
 *
 * \note The command IDs cannot be 0, since this value is reserved for no
 * command event callback for certain widgets.
 */
enum app_widget_ids {
	/** Event command ID for the slider. */
	SLIDER_ID = 1,
	/** Event command ID for the button. */
	BUTTON_ID,
};

/**
 * \name Color scheme
 *
 * @{
 */

/** Background color for application */
#define APP_BACKGROUND_COLOR        GFX_COLOR(50, 50, 50)

/** @} */

/**
 * \name Widget sizes and positions
 *
 * @{
 */

/** Label position on top of display */
#define LABEL_POS_X                 10
/** Label position on top of display */
#define LABEL_POS_Y                 10

/** Slider position */
#define SLIDER_POS_X                10
/** Slider position */
#define SLIDER_POS_Y                60
/** Slider size on display */
#define SLIDER_SIZE_X               80
/** Slider size on display */
#define SLIDER_SIZE_Y               40

/** Spacing from slider to progress bar */
#define SLIDER_PB_SPACING_X         10
/** Slider progress bar on display */
#define PB_SIZE_X                   SLIDER_SIZE_X
/** Slider progress bar on display */
#define PB_SIZE_Y                   SLIDER_SIZE_Y

/** @} */

/**
 * \name Widget configurations
 *
 * @{
 */

/** Max value for slider */
#define SLIDER_MAX_VALUE            100

/** @} */

/**
 * \name Static text strings
 *
 * @{
 */

/** Description for label */
const static char *demo_string = "Demonstrating widgets";

/** @} */

/**
 * \name Static variables
 *
 * @{
 */

/** Pointer to frame for application */
static struct wtk_basic_frame *main_frame;
/** Pointer to slider */
static struct wtk_slider *slider;
/** Pointer to progress bar */
static struct wtk_progress_bar *progress_bar;
/** Frame background bitmap */
static struct gfx_bitmap frame_background;
/** Counter for button */
static uint8_t counter;
/** Pointer to the sub-frame */
static struct wtk_basic_frame *sub_frame;
/** Sub-frame background bitmap */
static struct gfx_bitmap sub_frame_background;

/** @} */

/**
 * \brief Frame command events handler
 *
 * This function handles the command events generated by the widgets.
 *
 * \sa wtk_basic_frame_command_handler_t
 */
static bool widget_frame_command_handler(struct wtk_basic_frame *frame,
		win_command_t command_data)
{
	char command = (uintptr_t)command_data;

	switch (command) {
	case SLIDER_ID:
		wtk_progress_bar_set_value(progress_bar,
				wtk_slider_get_value(slider));
		break;

	case BUTTON_ID:
		/** \todo Add code here to handle button press. */
		counter++;
		win_redraw(wtk_basic_frame_as_child(sub_frame));
		break;
	}

	return false;
}

/**
 * \brief Frame draw event handler
 *
 * This function will draw the contents of the sub-frame.
 *
 * \sa wtk_basic_frame_draw_handler_t
 */
static void sub_frame_draw_handler(struct win_window *win,
		struct win_clip_region const *clip)
{
	char buffer[4];

	snprintf(buffer, sizeof(buffer), "%3d", counter);

	/**
	 * \todo Add code here to draw text on screen using the
	 * gfx_draw_string() function.
	 */
	gfx_draw_string(buffer, clip->origin.x + 30, clip->origin.y + 12,
			&sysfont, GFX_COLOR(255, 255, 255),
			GFX_COLOR_TRANSPARENT);
}

/**
 * \brief Setup widget demo
 *
 * This function launches the widget demo.
 */
void app_widget_launch()
{
	struct win_window *win_root;
	struct win_window *parent;
	struct win_area area;
	struct wtk_label *lbl;
	struct wtk_button *btn;

	/* Get pointer to root window */
	win_root = win_get_root();

	/* Application frame */

	/* Create a background bitmap using a solid color. */
	frame_background.type = GFX_BITMAP_SOLID;
	frame_background.data.color = APP_BACKGROUND_COLOR;

	/* Set the area to fill the entire screen */
	area.pos.x = 0;
	area.pos.y = 0;
	area.size.x = gfx_get_width();
	area.size.y = gfx_get_height();

	/*
	 * Create a basic frame with a specified background and command event
	 * handler. Check the return value if an error occurred while creating
	 * the widget.
	 */
	main_frame = wtk_basic_frame_create(win_root, &area,
			&frame_background, NULL,
			widget_frame_command_handler, NULL);
	if (!main_frame) {
		goto error_frame;
	}

	/* Get a pointer to the widget's window for adding sub-widgets. */
	parent = wtk_basic_frame_as_child(main_frame);

	/*
	 * Draw the frame by showing the frame widget's window. Any
	 * child-widgets and windows will not be shown before the parent
	 * widget/window is shown.
	 */
	win_show(parent);

	/* Application label */
	area.pos.x = LABEL_POS_X;
	area.pos.y = LABEL_POS_Y;
	/* Find an optimal size for the widget. */
	wtk_label_size_hint(&area.size, demo_string);

	/*
	 * Create the label and check the return value if an error occurred
	 * while creating the label.
	 */
	lbl = wtk_label_create(parent, &area, demo_string,
			GFX_COLOR(255, 255, 255), NULL, false);
	if (!lbl) {
		goto error_widget;
	}

	/* Draw the label by showing the label widget's window. */
	win_show(wtk_label_as_child(lbl));

	/* Application slider */
	area.pos.x = SLIDER_POS_X;
	area.pos.y = SLIDER_POS_Y;
	area.size.x = SLIDER_SIZE_X;
	area.size.y = SLIDER_SIZE_Y;

	/*
	 * Create the slider and check the return value if an error occurred
	 * while creating the slider.
	 */
	slider = wtk_slider_create(parent, &area, SLIDER_MAX_VALUE,
			SLIDER_MAX_VALUE / 2,
			WTK_SLIDER_HORIZONTAL | WTK_SLIDER_CMD_RELEASE,
			(win_command_t)SLIDER_ID);
	if (!slider) {
		goto error_widget;
	}

	/* Draw the slider by showing the slider widget's window. */
	win_show(wtk_slider_as_child(slider));

	/* Application progress bar, placed right of the slider. */
	area.pos.x += area.size.x + SLIDER_PB_SPACING_X;
	area.size.x = PB_SIZE_X;
	area.size.y = PB_SIZE_Y;

	/*
	 * Create the progress bar and check the return value if an error
	 * occurred while creating the progress bar.
	 */
	progress_bar = wtk_progress_bar_create(parent, &area, SLIDER_MAX_VALUE,
			SLIDER_MAX_VALUE / 2, GFX_COLOR(255, 255, 0),
			GFX_COLOR(90, 90, 90), WTK_PROGRESS_BAR_HORIZONTAL);
	if (!progress_bar) {
		goto error_widget;
	}

	/* Draw the progress bar by showing the progress bar widget's window. */
	win_show(wtk_progress_bar_as_child(progress_bar));

	/** \todo Add code to set up button here. */
	area.pos.x = 10;
	area.pos.y = 150;
	area.size.x = 90;
	area.size.y = 40;

	btn = wtk_button_create(parent, &area, "Click",
			(win_command_t)BUTTON_ID);
	if (!btn) {
		goto error_widget;
	}
	win_show(wtk_button_as_child(btn));

	/** \todo Add code to set up basic frame here. */
	area.pos.x += area.size.x + 40;

	sub_frame_background.type = GFX_BITMAP_SOLID;
	sub_frame_background.data.color = GFX_COLOR(127, 0, 0);

	sub_frame = wtk_basic_frame_create(parent, &area,
			&sub_frame_background, sub_frame_draw_handler,
			NULL, NULL);
	if (!sub_frame) {
		goto error_widget;
	}
	win_show(wtk_basic_frame_as_child(sub_frame));

	return;

error_widget:
	/* Destroy widget and all sub-widgets. */
	win_destroy(wtk_basic_frame_as_child(main_frame));
error_frame:
	/* Wait forever if an error occurred during setup. */
	while (1) {
	}
}
