/*
 * Generated by erpcgen 1.4.0 on Fri Jan 20 08:45:14 2017.
 *
 * AUTOGENERATED - DO NOT EDIT
 */

#if !defined(_erpc_remote_control_app_0_h_)
#define _erpc_remote_control_app_0_h_

// Common types header file
#include "erpc_remote_control.h"

/*! @brief remote_control_app_0 identifiers */
enum _remote_control_app_0_ids
{
    kremote_control_app_0_service_id = 1,
    kremote_control_app_0_get_board_config_id = 1,
    kremote_control_app_0_get_adc_config_id = 2,
    kremote_control_app_0_convert_dac_adc_id = 3,
    kremote_control_app_0_read_mag_accel_id = 4,
    kremote_control_app_0_set_led_id = 5,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! App 0: client part is on the PC, server on the board
//! @name remote_control_app_0
//@{
//! Get board configuration
void get_board_config(BoardConfig * config);

//! Get configuration for ADC
void get_adc_config(AdcConfig * config);

//! Convert number through DAC
void convert_dac_adc(uint32_t numberToConvert, uint32_t * result);

//! Read magnetometer and accelerometer data
void read_mag_accel(Vector * results, bool * status);

//! Turn on selected LED
void set_led(uint8_t whichLed);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _erpc_remote_control_app_0_h_
