/*
 * Generated by erpcgen 1.4.0 on Fri Jan 20 08:45:14 2017.
 *
 * AUTOGENERATED - DO NOT EDIT
 */

#if !defined(_erpc_remote_control_app_1_h_)
#define _erpc_remote_control_app_1_h_

// Common types header file
#include "erpc_remote_control.h"

/*! @brief remote_control_app_1 identifiers */
enum _remote_control_app_1_ids
{
    kremote_control_app_1_service_id = 2,
    kremote_control_app_1_button_pressed_id = 1,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name remote_control_app_1
//@{
//! Return which button was pressed
void button_pressed(uint32_t which);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _erpc_remote_control_app_1_h_
