/*
 * Generated by erpcgen 1.4.0 on Fri Jan 20 08:45:14 2017.
 *
 * AUTOGENERATED - DO NOT EDIT
 */

#if !defined(_erpc_remote_control_app_0_server_h_)
#define _erpc_remote_control_app_0_server_h_


#ifdef __cplusplus
#include "erpc_remote_control_app_0.h"
#include "server.h"
#include <stdint.h>
#include <stdbool.h>


/*!
 * @brief Service subclass for remote_control_app_0.
 */
class remote_control_app_0_service : public erpc::Service
{
public:
    remote_control_app_0_service() : Service(kremote_control_app_0_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for get_board_config of remote_control_app_0 interface. */
    erpc_status_t get_board_config_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for get_adc_config of remote_control_app_0 interface. */
    erpc_status_t get_adc_config_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for convert_dac_adc of remote_control_app_0 interface. */
    erpc_status_t convert_dac_adc_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for read_mag_accel of remote_control_app_0 interface. */
    erpc_status_t read_mag_accel_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for set_led of remote_control_app_0 interface. */
    erpc_status_t set_led_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#endif

typedef void * erpc_service_t;

erpc_service_t create_remote_control_app_0_service(void);
#ifdef __cplusplus
}
#endif

#endif // _erpc_remote_control_app_0_server_h_
