#
# Generated by erpcgen 1.4.0 on Fri Jan 20 08:45:14 2017.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# This const defines the matrix size. The value has to be the same as the
#Matrix array dimension. Do not forget to re-generate the erpc code once the
#matrix size is changed in the erpc file
matrix_size = 5


