#
# Generated by erpcgen 1.4.0 on Fri Jan 20 08:45:15 2017.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Abstract base class for remote_control_app_1
class Iremote_control_app_1(object):
    SERVICE_ID = 2
    BUTTON_PRESSED_ID = 1

   # Return which button was pressed
    def button_pressed(self, which):
        raise NotImplementedError()


