#
# Generated by erpcgen 1.4.0 on Fri Jan 20 08:45:14 2017.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Abstract base class for dac_adc
class Idac_adc(object):
    SERVICE_ID = 1
    ADC_GET_CONFIG_ID = 1
    CONVERT_DAC_ADC_ID = 2
    SET_LED_ID = 3
    READ_SENZOR_MAG_ACCEL_ID = 4
    BOARD_GET_NAME_ID = 5

    def adc_get_config(self, config):
        raise NotImplementedError()

    def convert_dac_adc(self, numberToConvert, result):
        raise NotImplementedError()

    def set_led(self, whichLed):
        raise NotImplementedError()

    def read_senzor_mag_accel(self, results):
        raise NotImplementedError()

    def board_get_name(self, name):
        raise NotImplementedError()


